title: Gus Guidry
email: me@gusguidry.com
description: > # this means to ignore newlines until "baseurl:"
  @gusguidry everywhere. Hello, my name is Gus Guidry. I blog in my spare time.
  Come visit! If you like what you see, subscribe to my RSS or follow me on any of my social links.
  Thank you very much!
url: "http://gusguidry.github.io"

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

# Conversion

highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge